########################################
## SHARED | deploykf-helpers
########################################
deployKF_helpers:
  deploykf_gateway:
    http_endpoint: "deploykf.stack8s.com"
    https_endpoint: "deploykf.stack8s.com"


########################################
## SHARED | deploykf
########################################
deployKF:
  extraManifests:

  clusterDomain: cluster.local

  kubeflow:
    namespace: kubeflow
    useridHeader: kubeflow-userid
    pipelines:
      enabled: true
      kfpV2:
        defaultPipelineRoot: "minio://{bucket_name}/v2/artifacts/{profile_name}"
      cache:
        namespaceRedirect: true

  certManager:
    clusterIssuer:
      issuerName: "deploykf-gateway-issuer"

  argoWorkflows:
    enabled: true
    namespace: "kubeflow-argo-workflows"
    artifactRepository:
      keyFormat: "artifacts/{{ workflow.namespace }}/{{ workflow.name }}/{{ workflow.creationTimestamp.Y }}/{{ workflow.creationTimestamp.m }}/{{ workflow.creationTimestamp.d }}/{{ pod.name }}"

  auth:
    namespace: "deploykf-auth"
    dex:
      clients:
        oauth2Proxy:
          clientId: "oauth2-proxy"
        kubeflowPipelinesSDK:
          enabled: true
          clientId: "kubeflow-pipelines-sdk"

  gateway:
    name: "deploykf-gateway"
    selectorLabels: {"app":"deploykf-gateway","istio":"deploykf-gateway"}
    hostname: "deploykf.stack8s.com"
    ports:
      http: 80
      https: 443
    tls:
      enabled: true
    enableProxyProtocol: false
    xffNumTrustedHops: 0
    emailToLowercase: false

  minio:
    enabled: true
    namespace: "deploykf-minio"


########################################
## DEPENDENCY | istio-gateway
########################################
## we reference the "gateway" chart (https://istio-release.storage.googleapis.com/charts) in `dependencies` of Chart.yaml
## we must indent our values under `gateway:` in this file
gatewayEnabled: true
gateway:
  name: "deploykf-gateway"

  replicaCount: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

  serviceAccount:
    name: "deploykf-gateway"
    annotations: {}

  service:
    annotations: {"service.beta.kubernetes.io/aws-load-balancer-type":"nlb"}
    type: "LoadBalancer"
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    externalTrafficPolicy: ""
    externalIPs: []
    ports:
      - name: status-port
        port: 15021
        protocol: TCP
        targetPort: 15021
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
      - name: https
        port: 443
        protocol: TCP
        targetPort: 443

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 1024Mi

  podAnnotations: {}

  securityContext: ~
  containerSecurityContext: ~

  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Pod environment variables
  env: {}

  # Labels to apply to all resources
  labels: {}

  # Annotations to apply to all resources
  annotations: {}